export const CHATBOT_START = "CHATBOT_START";
export const CHATBOT_ERROR = "CHATBOT_ERROR";
export const CHATBOT_SUCCESS = "CHATBOT_SUCCESS";
export const CHATBOT_DATA_SUCCESS = "CHATBOT_DATA_SUCCESS";
export const CHATBOT_ADD_SUCCESS = "CHATBOT_ADD_SUCCESS";
export const CHATBOT_DELETE_SUCCESS = "CHATBOT_DELETE_SUCCESS";